### ISSUE TITLE
Problème d'execution

### ISSUE THREAD

**Issue by crocoolivier** [Dfte/Discovery#1]
Salut, Voici ce que j'ai fait :

apt install -y python3-pip git dnsutils extract exiftool

pip3 install shodan python-nmap beautifulsoup4

git clone https://github.com/Dfte/Discovery.git
cd Discovery

git clone https://github.com/aboul3la/Sublist3r.git
--- Pas besoin les dépendances sont déjà installées --
cd Sublist3r
pip3 install -r requirements.txt
cd ..
-------
mv Sublist3r sublist3r

git clone https://github.com/rthalley/dnspython.git
cd dnspython
python3 setup.py install
cd ../
git clone https://github.com/joepie91/python-whois.git
cd python-whois
python3 setup.py install

git clone https://github.com/EnableSecurity/wafw00f.git

python3 discovery.py -d "google.fr"

et le script se ferme après avoir affiché les deux banners Celle avec le bateau et celle avec mischef. Rien d'autres :)
Je n'ai pas encore regardé le code. Comme je vois que tu es en train de mettre à jour ton installer, je voulais juste t'indiquer ce que j'ai fait.

**Comment by Dfte** [comment]
Hello, alors oui effectivement je modifie pas mal de choses là mais si le script ne fait rien c'est parce que tu n'as pas appellé les modules.
Pour avoir les entrées dns : --dns
Pour l'énumération de domaine : --sublist ou subrute
Pour la partie scan : --scan ["full" ou "fast"]
Pour la partie docment et metadatas : --gather
Pour l'harvesting : --harvest

Voilà voilà :)

Je mettrai à jour l'installer et le script au plus vite. Merci pour tes remontées :)

**Comment by crocoolivier** [comment]
ok  merci je vais tester ;)
